name: Build and deploy Python app to Azure Web App - entrainement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: Desktop/web

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Desktop/web
        
      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*
        working-directory: Desktop/web

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: Desktop/web/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C72D28C63DD54C4CAC405AAF42418E54 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8463D9A10BD4F28B2F5B35F2CCC2A4C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FAB68F083787425394FEF1BC912F13E9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'entrainement'
          slot-name: 'Production'
          package: .
